name: shelf_router_macro
description: Experimental support for shelf_router using macros
version: 0.0.0-dev.2
repository: https://github.com/eEQK/shelf_router_macro
topics: [server, shelf, macros]

environment:
  sdk: ^3.5.0-164.0.dev

dependencies:
  collection: ^1.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  macros: ^0.1.0-main.5
  meta: ^1.15.0

dev_dependencies:
  test: ^1.24.0
  matcher: ^0.12.16+1
  mocktail: ^1.0.3
